# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_code', models.IntegerField(null=True)),
                ('stop_name', models.CharField(max_length=128, null=True)),
                ('stop_desc', models.CharField(max_length=128, null=True)),
                ('stop_lat', models.FloatField(null=True)),
                ('stop_lon', models.FloatField(null=True)),
                ('zone_id', models.SmallIntegerField(null=True)),
                ('stop_url', models.CharField(max_length=128, null=True)),
                ('location_type', models.SmallIntegerField(null=True)),
                ('parent_station', models.IntegerField(null=True)),
                ('platform_code', models.CharField(max_length=2, null=True)),
                ('wheelchair_boarding', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=128, null=True)),
                ('arrival_time', models.TextField(null=True)),
                ('departure_time', models.TextField(null=True)),
                ('stop_id', models.IntegerField(null=True)),
                ('stop_sequence', models.SmallIntegerField(null=True)),
                ('pickup_type', models.SmallIntegerField(null=True)),
                ('drop_off_type', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'stop_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('route_id', models.CharField(max_length=128, null=True)),
                ('service_id', models.CharField(max_length=128, null=True)),
                ('trip_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(max_length=128, null=True)),
                ('trip_short_name', models.SmallIntegerField(null=True)),
                ('direction_id', models.SmallIntegerField(null=True)),
                ('block_id', models.CharField(max_length=128, null=True)),
                ('shape_id', models.CharField(max_length=128, null=True)),
                ('wheelchair_accessible', models.SmallIntegerField(null=True)),
                ('bikes_allowed', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'trip',
                'managed': False,
            },
        ),
    ]
